name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t tushar0123/springboot_application:first .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERU_NAME }} -p ${{ secrets.DOCKERU_PASS }}

      - name: Push Docker image to Docker Hub
        run: docker push  tushar0123/springboot_application:first
    

      - name: Deploy to EC2  
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{ secrets.HOST_IP }}
            USER_NAME: ${{ secrets.HOST_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
              
           cd /home/ubuntu &&
           sudo docker pull tushar0123/springboot_application:first &&
           sudo docker run -d -p 8081:8081 tushar0123/springboot_application:first --name springboot
          '
